openapi: 3.1.1
info:
  title: Library Management System API
  description: API for managing a library system will be changed to include books, authors, and users.
  version: "1.0.0"
  contact:
    email: "ahmedhesham11m@gmail.com"

servers:
  - url: http://localhost:8080/
paths: {}
